name: land_wiki
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  bloc: ^8.1.2
  cloud_firestore: ^4.8.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_tts: ^3.7.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  http: ^1.1.0
  shared_preferences: ^2.2.0
  sign_button: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  

